server:
  port: 8080
spring:
  application:
    name: ast-parser
    description: Java AST Parser with Spring Boot 3
  jackson:
    serialization:
      write-dates-as-timestamps: false
    visibility:
      getter: none
      is-getter: none
      setter: none
      field: any
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${OLLAMA_MODEL:qwen3:4b}
          temperature: 0.7
          top-p: 0.9

  # Neo4j 數據庫配置
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:12345678qwertyui}
    database: ${NEO4J_DATABASE:neo4j}
    connection:
      max-connection-pool-size: 50
      connection-acquisition-timeout: 30
      max-connection-lifetime: 3600
      connection-timeout: 30

# Swagger/OpenAPI 配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    display-request-duration: true
    display-operation-id: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    doc-expansion: none
    show-extensions: true
    show-common-extensions: true
  show-actuator: true

app:
  astDir: ${AST_DIR:${user.home}/git/01235711/01235711-javaparser/ast-parser/parsed-ast}
  tempBaseDir: ${TEMP_BASE_DIR:${user.home}/git/01235711/01235711-javaparser/ast-parser/tmp}
  debugMode: ${DEBUG_MODE:false}
  maxConcurrentTasks: ${MAX_CONCURRENT_TASKS:10}
  taskTimeoutSeconds: ${TASK_TIMEOUT_SECONDS:300}
  graph:
    exclude:
      annotation: ""
