server:
  port: 8080
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    visibility:
      getter: none
      is-getter: none
      setter: none
      field: any
  application:
    name: ast-parser
    description: Java AST Parser with Spring Boot 3
